Лабораторна робота №1
Безпоясний Денис ФІТ 4-8
Варіант 2

Завдання 1: Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та
виведіть його значення.


In [6]:
import numpy as np

vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
натуральними числами та виведіть його значення.


In [5]:
import numpy as np

matrix = np.random.randint(1, 101, size=(3, 3))
print(matrix)

[[21 78 62]
 [17 51 92]
 [37  1 30]]


Завдання 3: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від -1 до 1 та виведіть його значення.


In [8]:
import numpy as np

matrix = np.random.uniform(-1, 1, size=(5, 5))
print(matrix)

[[ 0.8227927   0.92985123 -0.10215655 -0.45680761 -0.98150493]
 [ 0.65437098 -0.54876432 -0.70928979 -0.89540905 -0.82946549]
 [ 0.81844781 -0.23773397  0.35219819 -0.57021677 -0.46461586]
 [ 0.68813355  0.74074923 -0.6203871  -0.7124957  -0.75119922]
 [-0.61467881  0.72341576 -0.08408574  0.07457265  0.24847675]]


Завдання 4: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє значення елементів.

In [13]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(5, 5))

average_value = np.mean(matrix)

print("Matrix:")
print(matrix)
print("Average:")
print(average_value)

Matrix:
[[0.56310981 0.25460505 0.03693438 0.35101459 0.3645308 ]
 [0.14444044 0.7299314  0.44323127 0.4286795  0.02204282]
 [0.47533297 0.06877944 0.05186375 0.56334624 0.02009576]
 [0.05188235 0.91222569 0.75485173 0.05302118 0.21337512]
 [0.99119911 0.68790604 0.98966122 0.68076651 0.65408502]]
Average:
0.42027648807028856


Завдання 5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання,
віднімання та множення.


In [17]:
import numpy as np

array1 = np.random.randint(-10, 11, size=5)
array2 = np.random.randint(-10, 11, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array1:")
print(array1)
print("Array1:")
print(array2)
print("Addition:")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication:")
print(multiplication)

Array1:
[ 2 -8  0 -3  7]
Array1:
[ -6 -10   4   1   1]
Addition:
[ -4 -18   4  -2   8]
Subtraction:
[ 8  2 -4 -4  6]
Multiplication:
[-12  80   0  -3   7]


Завдання 6: Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та
знайдіть їх добуток.

In [18]:
import numpy as np

matrix1 = np.random.uniform(3, 10, size=(2, 2))
matrix2 = np.random.uniform(3, 10, size=(2, 2))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[8.9009313  7.10117047]
 [3.08496297 6.91191695]]
Matrix2:
[[5.26886949 8.99383291]
 [3.59073668 3.57202141]]
Product:
[[ 72.3962787  105.41902191]
 [ 41.073141    52.43515683]]


Завдання 7: Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.


In [19]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix1:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[1 5 4]
 [3 2 2]]
Matrix1:
[[1 1]
 [1 4]
 [5 4]]
Product:
[[26 37]
 [15 19]]


Завдання 8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 12 та знайдіть її обернену матрицю.


In [20]:
import numpy as np

matrix = np.random.randint(1, 13, size=(3, 3))

print(matrix)

det = np.linalg.det(matrix)
if det == 0:
    print("Inverse matrix does not exist.")
else:
    inverse_matrix = np.linalg.inv(matrix)

    print("Inverse matrix:")
    print(inverse_matrix)

[[ 4  8  3]
 [ 1  6  8]
 [12 11  8]]
Inverse matrix:
[[-0.11080332 -0.08587258  0.12742382]
 [ 0.24376731 -0.01108033 -0.08033241]
 [-0.16897507  0.14404432  0.04432133]]


Завдання 9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -8 до 8 та транспонуйте її.

In [21]:
import numpy as np

matrix = np.random.uniform(-8, 8, size=(4, 4))
transposed_matrix = matrix.T

print(matrix)
print("Transposed matrix:")
print(transposed_matrix)

[[-3.57011969 -0.76318626  0.3356733  -5.44184049]
 [-6.89518941  0.1294196   6.83797277  5.04950596]
 [-6.3799367   7.19234534  6.45071806  7.16266067]
 [-2.0530754   7.08065234 -2.50812562 -3.21858109]]
Transposed matrix:
[[-3.57011969 -6.89518941 -6.3799367  -2.0530754 ]
 [-0.76318626  0.1294196   7.19234534  7.08065234]
 [ 0.3356733   6.83797277  6.45071806 -2.50812562]
 [-5.44184049  5.04950596  7.16266067 -3.21858109]]


Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.

In [22]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
average_value = np.mean(matrix)

print("Matrix:")
print(matrix)
print("Vector:")
print(vector)
print("Average value:")
print(average_value)

Matrix:
[[4 2 7 8]
 [3 2 5 8]
 [8 4 4 7]]
Vector:
[[ 7]
 [ 5]
 [10]
 [ 7]]
Average value:
5.166666666666667


Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.


In [23]:
import numpy as np

matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3, 1))
product = np.dot(matrix, vector)

print("Matrix:")
print(matrix)
print("Vector:")
print(vector)
print("Product:")
print(product)

Matrix:
[[7 2 6]
 [9 8 9]]
Vector:
[[0.32776182]
 [0.01521517]
 [0.05815639]]
Product:
[[2.67370142]
 [3.59498527]]


Завдання 12: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню різницю.


In [24]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))
difference = matrix1 - matrix2

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Difference:")
print(difference)

Matrix1:
[[6 8 2]
 [8 1 1]
 [4 5 1]]
Matrix2:
[[10  2  2]
 [ 3  1  7]
 [ 9  7  3]]
Difference:
[[-4  6  0]
 [ 5  0 -6]
 [-5 -2 -2]]


Завдання 13: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть їх добуток.

In [25]:
import numpy as np

matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[ 0  4 -4]
 [ 2 -4 -3]
 [-1  3  4]]
Matrix2:
[[-5  2  0]
 [ 4  1  4]
 [ 1  4  5]]
Product:
[[ 12 -12  -4]
 [-29 -12 -31]
 [ 21  17  32]]


Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від -5 до 5 та знайдіть суму елементів матриці.

In [27]:
import numpy as np

matrix = np.random.randint(-5, 6, size=(3, 3))
sum_of_elements = np.sum(matrix)

print(matrix)
print("Sum:")
print(sum_of_elements)

[[ 3  5  4]
 [ 2  3  1]
 [-3 -1  3]]
Sum:
17


Завдання 15: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів
кожного рядка матриці.

In [28]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(4, 4))
row_products = np.prod(matrix, axis=1)
column_vector = row_products.reshape(-1, 1)

print(matrix)
print("Column vector:")
print(column_vector)

[[0.12811256 0.31367574 0.03533365 0.4383694 ]
 [0.57734768 0.8750216  0.65302572 0.98817678]
 [0.10629756 0.73425931 0.76975195 0.95255439]
 [0.0107188  0.4006424  0.37817685 0.86489874]]
Column vector:
[[0.00062245]
 [0.32600265]
 [0.05722863]
 [0.00140463]]
